feat: add vercel preview in README.md
fabian37/BLOG_UI_TEMPLATE pull request #5
Opened 2022-12-27 02:21 UTC by fabian37

Hola @neriheredia agregó la preview del proyecto solicita en el README

2022-12-27 09:18 UTC, neriheredia requested changes

2022-12-27 09:18 UTC, neriheredia commented on README.md
> +https://blog-ui-template-fabian37.vercel.app/
Yo diría que no correr el otro para guiarte en lo que falta y aparte agregues el tuyo nuevo Fabián que opinas?

2022-12-27 18:35 UTC, fabian37 commented on README.md
> +https://blog-ui-template-fabian37.vercel.app/
Si dale Neri no hay problema, igual cuando ya se vaya a terminar el proyecto supondré que lo saco

2022-12-28 10:33 UTC, neriheredia approved these changes

2022-12-29 00:03 UTC, merged