feat: add sidebar
fabian37/BLOG_UI_TEMPLATE pull request #7
Opened 2022-12-28 04:56 UTC by fabian37

Hola Neri agregó el asidebar y adicionalmente mejoré el responsive de los posts y el asidebar.

2023-01-02 17:37 UTC, heredialucas commented on src/components/sidebar/Sidebar.module.css
> +}
No resulta un poco redundante el empezar todos los nombres de los estilos con sidebar? Pregunto esto porq los modules funcionan únicamente para el componente q está dentro de su misma estructura de carpetas ( o por lo menos eso veo que hiciste )

2023-01-02 17:40 UTC, heredialucas commented on src/components/sidebar/Sidebar.module.css
> +}
Trataría de hacer un archivo que te sirva de utilidad para manejar las fuentes, tamaños, colores, etc.
Esto para poder usarlo en toda la app, y también tener algo mucho mas legíble, y no mezclar pixeles con rem por ejemplo

2023-01-02 17:42 UTC, heredialucas requested changes

2023-01-02 17:42 UTC, heredialucas commented on src/pages/home/Home.jsx
>  );
El diseño planteado no está como el original 
![Captura de pantalla_20230102_144037](https://user-images.githubusercontent.com/77968538/210264200-c69e0f0c-6647-402d-b172-147021982f6b.png)
![Captura de pantalla_20230102_144206](https://user-images.githubusercontent.com/77968538/210264244-b8ecf46b-589e-4288-bb6d-91c84b4842a4.png)

2023-01-03 16:04 UTC, fabian37 commented on src/components/sidebar/Sidebar.module.css
> +}
Hola Lucas, lo puse así para tratar de ser muy específico y tal vez que fuera más fácil migrar de tecnica de CSS, entonces voy a simplificar más las clases

2023-01-03 16:07 UTC, fabian37 commented on src/components/sidebar/Sidebar.module.css
> +}
Listo Lucas me parece una muy buena idea

2023-01-16 13:56 UTC, CasadoFrancisco commented
hola fabi

2023-01-16 13:59 UTC, merged